name: Build Biblioteca IA

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev python3-pyaudio
        
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller  # Asegurar que está instalado
        
    - name: Build Linux executable
      run: |
        python build.py
        
    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BibliotecaIA-Linux
        path: |
          dist/BibliotecaIA
          config/
          resources/

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller  # Asegurar que está instalado
        
    - name: Build Windows executable
      run: |
        python build.py
        
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BibliotecaIA-Windows
        path: |
          dist/BibliotecaIA.exe
          config/
          resources/